Numpy starts for numerical python.

it is used to do mathematical operations


In [ ]:
import numpy as np

Numpy Arrays

In [ ]:
#List

In [ ]:
list1 =[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,6])
print(np_array)
type(np_array)

[1 2 3 4 6]


numpy.ndarray

In [ ]:
#creating a one dimensional array
a = np.array([3,4,5,6,7])
print(a)

[3 4 5 6 7]


In [ ]:
#checking the shape.in other words rows and columns in the array.
a.shape

(5,)

In [ ]:
#creating a two dimensional array
b = np.array([(2,3,4,1),(9,8,7,5)])
print(b)


[[2 3 4 1]
 [9 8 7 5]]


In [ ]:
b.shape

(2, 4)

In [ ]:
#creating an array with floating points
c = np.array ([(5,3,1,9),(7,6,3,8)],dtype=float)
print(c)

[[5. 3. 1. 9.]
 [7. 6. 3. 8.]]


Intial placeholders in Numpy arrays

In [ ]:
#creating a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#creating a numpy array of ones
y = np.ones((3,3))
print(y)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#creating an array with a particular value
z = np.full((5,4),7)
print(z)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
#creating an identity matrix
# we use the key word np.eye
a = np.eye(4)
print(a)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.13724125 0.57348686 0.40759923 0.62717488]
 [0.67769813 0.81843048 0.87523653 0.0768511 ]
 [0.35589676 0.44454348 0.65729363 0.58545678]]


In [ ]:
#creating random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)


[[57 85 69 25 83]
 [20 95 25 24 80]
 [38 54 47 61 59]]


In [ ]:
#creating an array of evenly spaced values .....specifying the number of values required
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
#array of evenly spaced values .....specifying the step
e = np.arange(30,100,10)
print(e)

[30 40 50 60 70 80 90]


Converting a list to a numpy array

In [ ]:
list2 = [20,37,40,43,]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[20 37 40 43]


numpy.ndarray

Analyzing a numpy array

In [ ]:
g = np.random.randint(10,100,(5,5))
print(g)


[[88 45 86 69 21]
 [25 75 52 76 92]
 [51 54 69 90 77]
 [28 54 79 20 66]
 [44 94 14 93 23]]


In [ ]:
#array dimension
print(g.shape)

(5, 5)


In [ ]:
#number of dimensions
print(g.ndim)

2


In [ ]:
#checking the number of elements in an array
print(g.size)

25


In [ ]:
#checking the data type of the values in the array
print(g.dtype)

int64


Mathematical operations in a numpy array

In [ ]:
list1 = [5,4,3,2,3,1]
list2 = [6,8,9,7,3,2]
print(list1 + list2)

[5, 4, 3, 2, 3, 1, 6, 8, 9, 7, 3, 2]


In [ ]:
n = np.random.randint(0,10,(3,3))
m = np.random.randint(10,20(3,3))
print(n)
print(m)

<>:2: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:2: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<ipython-input-39-77ad028b721c>:2: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  m = np.random.randint(10,20(3,3))


TypeError: 'int' object is not callable

In [ ]:
m = np.random.randint(0,10,(3,3))
n = np.random.randint(10,20,(3,3))

In [ ]:
print(m)
print(n)

[[1 3 1]
 [6 9 5]
 [5 8 4]]
[[12 13 12]
 [14 13 11]
 [11 17 11]]


In [ ]:
print(m+n)

[[13 16 13]
 [20 22 16]
 [16 25 15]]


In [ ]:
print(n/m)

[[12.          4.33333333 12.        ]
 [ 2.33333333  1.44444444  2.2       ]
 [ 2.2         2.125       2.75      ]]


In [ ]:
print(n-m)

[[11 10 11]
 [ 8  4  6]
 [ 6  9  7]]


In [ ]:
print(n*m)

[[ 12  39  12]
 [ 84 117  55]
 [ 55 136  44]]


In [ ]:
m = np.random.randint(0,10,(3,3))
n = np.random.randint(10,20,(3,3))

In [ ]:
print(m)
print(n)

[[0 8 5]
 [3 1 4]
 [6 2 6]]
[[17 14 14]
 [16 13 18]
 [18 14 12]]


In [ ]:
print(np.add(m,n))
print(np.subtract(m,n))
print(np.multiply(m,n))
print(np.divide(m,n))


[[17 22 19]
 [19 14 22]
 [24 16 18]]
[[-17  -6  -9]
 [-13 -12 -14]
 [-12 -12  -6]]
[[  0 112  70]
 [ 48  13  72]
 [108  28  72]]
[[0.         0.57142857 0.35714286]
 [0.1875     0.07692308 0.22222222]
 [0.33333333 0.14285714 0.5       ]]


Array Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 6 2]
 [0 6 1]]
(2, 3)


In [ ]:
#creating the transponse
#the rows becomes the columns and the columns becomes the rows
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[9 0]
 [6 6]
 [2 1]]
(3, 2)


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 7 8]
 [6 9 4]]
(2, 3)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[5 6]
 [7 9]
 [8 4]]
(3, 2)


In [ ]:
#reshaping an array
h = np.random.randint(0,10,(2,3))
print(h)
print(h.shape)

[[8 1 6]
 [7 3 9]]
(2, 3)


In [ ]:
b = h.reshape(3,2)


In [ ]:
print(b)

[[8 1]
 [6 7]
 [3 9]]


In [ ]:
print(b.shape)

(3, 2)
